# Generated by Django 5.2 on 2025-05-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CptTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeotechnicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('npv', models.FloatField(default=0)),
                ('npv_max', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CptData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(default=0)),
                ('qc', models.FloatField(default=0)),
                ('fs', models.FloatField(default=0)),
                ('u', models.FloatField(default=0)),
                ('cpt_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='geotech.cpttest')),
            ],
        ),
        migrations.AddField(
            model_name='cpttest',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpt_tests', to='geotech.geotechnicalmodel'),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('depth', models.FloatField(default=0)),
                ('unit_weight', models.FloatField(default=18)),
                ('cohesion', models.FloatField(default=0)),
                ('friction_angle', models.FloatField(default=0)),
                ('compressibility', models.FloatField(default=0)),
                ('permeability', models.FloatField(blank=True, null=True)),
                ('cpt_data', models.TextField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='geotech.geotechnicalmodel')),
            ],
        ),
    ]
