# Generated by Django 5.2 on 2025-05-06 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CptTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CptData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(default=0)),
                ('qc', models.FloatField(default=0)),
                ('fs', models.FloatField(default=0)),
                ('u', models.FloatField(default=0)),
                ('cpt_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='geotech.cpttest')),
            ],
        ),
        migrations.CreateModel(
            name='GeotechnicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('npv', models.FloatField(default=0)),
                ('npv_max', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='geotech.object')),
            ],
        ),
        migrations.AddField(
            model_name='cpttest',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpt_tests', to='geotech.geotechnicalmodel'),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('depth', models.FloatField(default=0)),
                ('unit_weight', models.FloatField(default=18)),
                ('cohesion', models.FloatField(default=0)),
                ('friction_angle', models.FloatField(default=0)),
                ('compressibility', models.FloatField(default=0)),
                ('permeability', models.FloatField(blank=True, null=True)),
                ('cpt_data', models.TextField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='geotech.geotechnicalmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='geotech.project'),
        ),
        migrations.AddField(
            model_name='geotechnicalmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='geotech.project'),
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='geotechnicalmodel',
            unique_together={('object', 'name')},
        ),
    ]
