# Generated by Django 5.2 on 2025-05-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geotech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
