# Generated by Django 5.2 on 2025-05-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geotech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cptdata',
            old_name='u',
            new_name='u2',
        ),
    ]
